"""
Rule sets. Each rule references a field in the normalized model.
"""

CIS_RULES = [
    {"id": "CIS-01", "name": "Telnet Disabled", "field": "telnet_enabled",
     "expected": False, "severity": "High",
     "expected_text": "Telnet must be disabled. SSH should be used for remote administration.",
     "description": "Telnet transmits credentials and session data in cleartext.",
     "remediation_meaning": "Removes Telnet from the allowed remote-access protocols on the vty lines, forcing SSH.",
     "remediation": {"cisco": "line vty 0 4\n transport input ssh",
                     "juniper": "delete system services telnet",
                     "fortinet": "config system interface\n edit <intf>\n set allowaccess https ssh\nend"}},

    {"id": "CIS-02", "name": "SSH Version 2 Enforced", "field": "ssh_version",
     "expected": 2, "severity": "High",
     "expected_text": "SSH version 2 must be the only version permitted.",
     "description": "SSHv1 has known cryptographic weaknesses; only SSHv2 should be permitted.",
     "remediation_meaning": "Forces SSH to negotiate only the v2 protocol, eliminating downgrade attacks.",
     "remediation": {"cisco": "ip ssh version 2",
                     "juniper": "set system services ssh protocol-version v2",
                     "fortinet": "config system global\n set admin-ssh-v1 disable\nend"}},

    {"id": "CIS-03", "name": "HTTP Management Disabled", "field": "http_mgmt_enabled",
     "expected": False, "severity": "Medium",
     "expected_text": "Unencrypted HTTP management must be disabled.",
     "description": "Unencrypted HTTP management exposes credentials and session data.",
     "remediation_meaning": "Turns off the unencrypted web admin interface; only HTTPS remains.",
     "remediation": {"cisco": "no ip http server",
                     "juniper": "delete system services web-management http",
                     "fortinet": "config system interface\n edit <intf>\n set allowaccess https ssh\nend"}},

    {"id": "CIS-04", "name": "HTTPS Management Enabled", "field": "https_mgmt_enabled",
     "expected": True, "severity": "Medium",
     "expected_text": "Encrypted HTTPS management must be available.",
     "description": "Encrypted management access should be available as the secure alternative to HTTP.",
     "remediation_meaning": "Enables the encrypted web admin interface as the secure replacement for HTTP.",
     "remediation": {"cisco": "ip http secure-server",
                     "juniper": "set system services web-management https",
                     "fortinet": "config system interface\n edit <intf>\n set allowaccess https\nend"}},

    {"id": "CIS-05", "name": "Password Encryption Enabled", "field": "password_encryption",
     "expected": True, "severity": "High",
     "expected_text": "Locally stored passwords must be encrypted, not stored in plaintext.",
     "description": "Locally stored passwords must be encrypted, not stored in plaintext.",
     "remediation_meaning": "Enables hashing of locally stored passwords in the configuration.",
     "remediation": {"cisco": "service password-encryption",
                     "juniper": "set system login user <user> authentication encrypted-password <hash>",
                     "fortinet": "(platform default - verify with: show system admin)"}},

    {"id": "CIS-06", "name": "Minimum Password Length >= 8", "field": "min_password_length",
     "expected": (">=", 8), "severity": "Medium",
     "expected_text": "Minimum password length must be at least 8 characters.",
     "description": "Weak minimum password length increases brute-force risk.",
     "remediation_meaning": "Sets the minimum required length for local passwords to 8 characters.",
     "remediation": {"cisco": "security passwords min-length 8",
                     "juniper": "set system login password minimum-length 8",
                     "fortinet": "config system password-policy\n set minimum-length 8\nend"}},

    {"id": "CIS-07", "name": "Login Banner Configured", "field": "banner_configured",
     "expected": True, "severity": "Low",
     "expected_text": "A legal/warning banner must be displayed before authentication.",
     "description": "A legal/warning banner should be presented before authentication.",
     "remediation_meaning": "Displays a legal warning to anyone connecting, before they authenticate.",
     "remediation": {"cisco": 'banner motd ^C Authorized access only. ^C',
                     "juniper": 'set system login message "Authorized access only."',
                     "fortinet": "config system global\n set pre-login-banner enable\nend"}},

    {"id": "CIS-08", "name": "Session Idle Timeout <= 10 min", "field": "exec_timeout_minutes",
     "expected": ("<=", 10), "severity": "Medium",
     "expected_text": "Idle administrative sessions must time out within 10 minutes.",
     "description": "Idle admin sessions should time out to reduce hijack risk.",
     "remediation_meaning": "Terminates an admin session after 10 minutes of inactivity.",
     "remediation": {"cisco": "line vty 0 4\n exec-timeout 10 0",
                     "juniper": "set system login idle-timeout 10",
                     "fortinet": "config system global\n set admintimeout 10\nend"}},

    {"id": "CIS-09", "name": "Centralized Logging Enabled", "field": "logging_enabled",
     "expected": True, "severity": "High",
     "expected_text": "Administrative and security events must be sent to a central syslog server.",
     "description": "Administrative access and events must be logged for audit/forensics.",
     "remediation_meaning": "Forwards device logs to a central syslog server for audit and forensics.",
     "remediation": {"cisco": "logging host <syslog-server-ip>\nlogging trap informational",
                     "juniper": "set system syslog host <syslog-server-ip> any any",
                     "fortinet": "config log syslogd setting\n set status enable\n set server <syslog-server-ip>\nend"}},

    {"id": "CIS-10", "name": "NTP Configured", "field": "ntp_configured",
     "expected": True, "severity": "Medium",
     "expected_text": "NTP time synchronization must be configured.",
     "description": "Accurate time sync is required for reliable log correlation.",
     "remediation_meaning": "Syncs the device clock to an NTP server so log timestamps are accurate.",
     "remediation": {"cisco": "ntp server <ntp-server-ip>",
                     "juniper": "set system ntp server <ntp-server-ip>",
                     "fortinet": "config system ntp\n set ntpsync enable\n set server <ntp-server-ip>\nend"}},

    {"id": "CIS-11", "name": "Centralized Authentication (AAA) Configured", "field": "aaa_configured",
     "expected": True, "severity": "Medium",
     "expected_text": "Authentication must be centralized via AAA/RADIUS/TACACS+.",
     "description": "Authentication should be centralized (AAA/RADIUS/TACACS+), not local-only.",
     "remediation_meaning": "Enables centralized authentication via RADIUS/TACACS+ instead of local-only accounts.",
     "remediation": {"cisco": "aaa new-model",
                     "juniper": "set system authentication-order [ radius password ]",
                     "fortinet": "config user radius\n edit <server>\n set server <radius-ip>\nend"}},

    {"id": "CIS-12", "name": "Management Access Restricted via ACL", "field": "vty_acl_applied",
     "expected": True, "severity": "High",
     "expected_text": "Administrative interfaces must be restricted to trusted source addresses.",
     "description": "Administrative interfaces must be restricted to trusted source addresses.",
     "remediation_meaning": "Restricts administrative access to a whitelist of trusted source IP ranges.",
     "remediation": {"cisco": "access-list 10 permit <trusted-subnet>\nline vty 0 4\n access-class 10 in",
                     "juniper": "set firewall filter PROTECT-RE term allow-mgmt from source-address <trusted-subnet>",
                     "fortinet": "config system interface\n edit <intf>\n set trusthost1 <trusted-subnet>\nend"}},

    {"id": "CIS-13", "name": "No Default/Weak SNMP Community Strings", "field": "weak_snmp_community_detected",
     "expected": False, "severity": "High",
     "expected_text": "SNMP community strings must not be the defaults (public/private).",
     "description": "Default community strings (public/private) allow unauthorized SNMP access.",
     "remediation_meaning": "Replaces the default 'public'/'private' SNMP community string with a strong custom one.",
     "remediation": {"cisco": "no snmp-server community public\nsnmp-server community <strong-string> RO",
                     "juniper": "set snmp community <strong-string> authorization read-only",
                     "fortinet": "config system snmp community\n edit 1\n set name <strong-string>\nend"}},

    {"id": "CIS-14", "name": "Account Lockout Policy Configured", "field": "login_lockout_configured",
     "expected": True, "severity": "Medium",
     "expected_text": "A login lockout policy must be configured.",
     "description": "Repeated failed logins should trigger a lockout to slow brute-force attempts.",
     "remediation_meaning": "Blocks further login attempts for 120 seconds after 3 failed attempts within 60 seconds.",
     "remediation": {"cisco": "login block-for 120 attempts 3 within 60",
                     "juniper": "set system login retry-options tries-before-disconnect 3",
                     "fortinet": "config system global\n set admin-lockout-threshold 3\nend"}},
]


NIST_RULES = [
    {"id": "NIST-AC-17", "name": "Remote Access Encryption (SSHv2)", "field": "ssh_version",
     "expected": 2, "severity": "High",
     "expected_text": "Remote access must use encryption (SSHv2).",
     "description": "NIST SP 800-53 AC-17: remote access must use encrypted protocols.",
     "remediation_meaning": "Forces SSH v2 to comply with AC-17's encryption requirement.",
     "remediation": {"cisco": "ip ssh version 2", "juniper": "set system services ssh protocol-version v2",
                     "fortinet": "config system global\n set admin-ssh-v1 disable\nend"}},

    {"id": "NIST-CM-7", "name": "Insecure Remote Access Disabled", "field": "telnet_enabled",
     "expected": False, "severity": "High",
     "expected_text": "Telnet (non-essential insecure service) must be disabled.",
     "description": "NIST CM-7: restrict functionality to least required. Telnet must be disabled.",
     "remediation_meaning": "Removes Telnet from the vty lines, complying with least-functionality.",
     "remediation": {"cisco": "line vty 0 4\n transport input ssh", "juniper": "delete system services telnet",
                     "fortinet": "config system interface\n edit <intf>\n set allowaccess https ssh\nend"}},

    {"id": "NIST-SC-8", "name": "Encrypted Management Channel", "field": "http_mgmt_enabled",
     "expected": False, "severity": "Medium",
     "expected_text": "Management traffic must be encrypted.",
     "description": "NIST SC-8: transmission confidentiality. HTTP management is unencrypted.",
     "remediation_meaning": "Disables unencrypted HTTP management, complying with SC-8.",
     "remediation": {"cisco": "no ip http server", "juniper": "delete system services web-management http",
                     "fortinet": "config system interface\n edit <intf>\n set allowaccess https ssh\nend"}},

    {"id": "NIST-SC-8b", "name": "Secure Management Channel Available", "field": "https_mgmt_enabled",
     "expected": True, "severity": "Medium",
     "expected_text": "Encrypted HTTPS management must be available.",
     "description": "NIST SC-8: encrypted management must be available.",
     "remediation_meaning": "Enables HTTPS management as the encrypted alternative.",
     "remediation": {"cisco": "ip http secure-server", "juniper": "set system services web-management https",
                     "fortinet": "config system interface\n edit <intf>\n set allowaccess https\nend"}},

    {"id": "NIST-IA-5", "name": "Authenticator Management - Password Length", "field": "min_password_length",
     "expected": (">=", 8), "severity": "Medium",
     "expected_text": "Minimum password length must be at least 8.",
     "description": "NIST IA-5: enforce minimum password complexity.",
     "remediation_meaning": "Enforces 8-character minimum passwords, complying with IA-5.",
     "remediation": {"cisco": "security passwords min-length 8", "juniper": "set system login password minimum-length 8",
                     "fortinet": "config system password-policy\n set minimum-length 8\nend"}},

    {"id": "NIST-IA-5b", "name": "Password Encryption at Rest", "field": "password_encryption",
     "expected": True, "severity": "High",
     "expected_text": "Stored authenticators must be cryptographically protected.",
     "description": "NIST IA-5: protect stored authenticators cryptographically.",
     "remediation_meaning": "Enables hashing of stored passwords, complying with IA-5.",
     "remediation": {"cisco": "service password-encryption",
                     "juniper": "set system login user <user> authentication encrypted-password <hash>",
                     "fortinet": "(platform default - verify with: show system admin)"}},

    {"id": "NIST-AC-11", "name": "Session Lock / Idle Timeout", "field": "exec_timeout_minutes",
     "expected": ("<=", 10), "severity": "Medium",
     "expected_text": "Sessions must lock after 10 minutes of inactivity.",
     "description": "NIST AC-11: sessions must lock after defined inactivity.",
     "remediation_meaning": "Auto-locks idle sessions after 10 minutes, complying with AC-11.",
     "remediation": {"cisco": "line vty 0 4\n exec-timeout 10 0", "juniper": "set system login idle-timeout 10",
                     "fortinet": "config system global\n set admintimeout 10\nend"}},

    {"id": "NIST-AU-2", "name": "Audit Logging Enabled", "field": "logging_enabled",
     "expected": True, "severity": "High",
     "expected_text": "Audit events must be generated and retained.",
     "description": "NIST AU-2: audit events must be generated and retained.",
     "remediation_meaning": "Sends audit logs to a central server, complying with AU-2.",
     "remediation": {"cisco": "logging host <syslog-server-ip>\nlogging trap informational",
                     "juniper": "set system syslog host <syslog-server-ip> any any",
                     "fortinet": "config log syslogd setting\n set status enable\n set server <syslog-server-ip>\nend"}},

    {"id": "NIST-AU-8", "name": "Time Synchronization", "field": "ntp_configured",
     "expected": True, "severity": "Medium",
     "expected_text": "Time synchronization must be configured.",
     "description": "NIST AU-8: reliable timestamps require accurate time source.",
     "remediation_meaning": "Syncs the device clock for accurate audit timestamps (AU-8).",
     "remediation": {"cisco": "ntp server <ntp-server-ip>", "juniper": "set system ntp server <ntp-server-ip>",
                     "fortinet": "config system ntp\n set ntpsync enable\n set server <ntp-server-ip>\nend"}},

    {"id": "NIST-AC-7", "name": "Unsuccessful Login Attempts Limited", "field": "login_lockout_configured",
     "expected": True, "severity": "Medium",
     "expected_text": "Consecutive invalid login attempts must be limited.",
     "description": "NIST AC-7: limit consecutive invalid login attempts.",
     "remediation_meaning": "Locks the account after 3 failed login attempts (AC-7).",
     "remediation": {"cisco": "login block-for 120 attempts 3 within 60",
                     "juniper": "set system login retry-options tries-before-disconnect 3",
                     "fortinet": "config system global\n set admin-lockout-threshold 3\nend"}},

    {"id": "NIST-SI-4", "name": "No Weak Default SNMP Communities", "field": "weak_snmp_community_detected",
     "expected": False, "severity": "High",
     "expected_text": "Default SNMP community strings must not be used.",
     "description": "NIST SI-4: monitoring channels must not use default credentials.",
     "remediation_meaning": "Replaces default SNMP community strings with strong ones (SI-4).",
     "remediation": {"cisco": "no snmp-server community public\nsnmp-server community <strong-string> RO",
                     "juniper": "set snmp community <strong-string> authorization read-only",
                     "fortinet": "config system snmp community\n edit 1\n set name <strong-string>\nend"}},

    {"id": "NIST-AC-4", "name": "Management Access Restricted", "field": "vty_acl_applied",
     "expected": True, "severity": "High",
     "expected_text": "Management access must be restricted to trusted sources.",
     "description": "NIST AC-4: information flow control - management interfaces must be restricted.",
     "remediation_meaning": "Applies an ACL restricting management to trusted source IPs (AC-4).",
     "remediation": {"cisco": "access-list 10 permit <trusted-subnet>\nline vty 0 4\n access-class 10 in",
                     "juniper": "set firewall filter PROTECT-RE term allow-mgmt from source-address <trusted-subnet>",
                     "fortinet": "config system interface\n edit <intf>\n set trusthost1 <trusted-subnet>\nend"}},

    {"id": "NIST-IA-2", "name": "Centralized Authentication", "field": "aaa_configured",
     "expected": True, "severity": "Medium",
     "expected_text": "Centralized authentication must be configured.",
     "description": "NIST IA-2: identification and authentication - centralized AAA preferred.",
     "remediation_meaning": "Enables AAA/RADIUS centralized authentication (IA-2).",
     "remediation": {"cisco": "aaa new-model", "juniper": "set system authentication-order [ radius password ]",
                     "fortinet": "config user radius\n edit <server>\n set server <radius-ip>\nend"}},

    {"id": "NIST-AC-8", "name": "System Use Notification (Banner)", "field": "banner_configured",
     "expected": True, "severity": "Low",
     "expected_text": "A system use notification must be displayed before login.",
     "description": "NIST AC-8: system use notification before login.",
     "remediation_meaning": "Displays a legal notification before login (AC-8).",
     "remediation": {"cisco": 'banner motd ^C Authorized access only. ^C',
                     "juniper": 'set system login message "Authorized access only."',
                     "fortinet": "config system global\n set pre-login-banner enable\nend"}},
]


FRAMEWORKS = {
    "CIS": CIS_RULES,
    "NIST": NIST_RULES,
}